image: debian:testing

reflow:
  stage: test
  script:
    - apt update -y -qq && apt install -y -qq --no-install-recommends make python3 diffutils
    - make check-reflow

codespell:
  stage: test
  script:
    - apt update -y -qq && apt install -y -qq --no-install-recommends make codespell
    - make codespell

pages:
  stage: deploy
  script:
    - find /etc/apt -name '*.list' -exec sed -i 's/main/main non-free/' {} \; # xml2rfc is non-free
    - "find /etc/apt -name '*.sources' -exec sed -i 's/^Components:/Components: non-free/' {} ';'"
    - apt update -y -qq && apt install -y -qq --no-install-recommends make weasyprint xml2rfc ruby-kramdown-rfc2629
    - make crypto-refresh.xml
    - mkdir public
    - cp crypto-refresh.xml public/draft-ietf-openpgp-crypto-refresh.xml
    - "sed -i 's/^docname: draft-ietf-openpgp-crypto-refresh-.*/docname: draft-ietf-openpgp-crypto-refresh-latest/' crypto-refresh.md"
    - make crypto-refresh.html
    - cp -v crypto-refresh.html public/index.html
  cache:
    paths:
      - .refcache
  artifacts:
    paths:
      - public
  only:
    - main
  variables:
    DEBIAN_FRONTEND: noninteractive
