#!/usr/bin/python3
import sys
import re
data = sys.stdin.read()
# strip out the page delimiters:
data = re.compile(r'\n+Koch, et al. +Expires .* +\[Page .*\]\n\x0c\nInternet-Draft +OpenPGP Message Format +September 2019\n+', re.M).sub('\n', data)
# collapse multiple blank lines into a single blank line:
data = re.compile(r'\n\n+', re.M).sub('\n\n', data)
# standardize bullet headings:
data = re.compile(r'^   o  ', re.M).sub('   *  ', data)
data = re.compile(r'^      \*  ', re.M).sub('      -  ', data)
data = re.compile(r'^         \+  ', re.M).sub('         o  ', data)
sys.stdout.write(data)
